### ISSUE TITLE
ARM64 package

### ISSUE THREAD

**Issue by Spasman** [glankk/n64#22]
hi, i am unable to push ultra-n64 to my macbook M2 due to a lacking repository, any alternative branch i can switch to or am i up a creek?

![Screenshot 2024-11-24 at 8 52 31 PM](https://github.com/user-attachments/assets/f8584061-b076-4002-8c43-543d5cad25c2)

**Comment by glankk** [comment]
Sorry, there are no prebuilt packages for arm at the moment.

**Comment by Spasman** [comment]
No problem, thank you for answering
