### ISSUE TITLE
Checking for Suffix of Object Files Error

### ISSUE THREAD

**Issue by shawlucas** [glankk/n64#8]
Hi,
Attempting to build with `sudo make -j4 install-toolchain` on Ubuntu 18.04.2 LTS, getting this:

`checking for mips64-gcc... /home/lucas/n64-master/build-gcc/./gcc/xgcc -B/home/lucas/n64-master/build-gcc/./gcc/ -B/opt/n64/mips64/bin/ -B/opt/n64/mips64/lib/ -isystem /opt/n64/mips64/include -isystem /opt/n64/mips64/sys-include   
checking for suffix of object files... configure: error: in /home/lucas/n64-master/build-gcc/mips64/libgcc:
configure: error: cannot compute suffix of object files: cannot compile
See config.log for more details
Makefile:13448: recipe for target configure-target-libgcc failed
make[2]: *** [configure-target-libgcc] Error 1
make[2]: Leaving directory /home/lucas/n64-master/build-gcc
Makefile:957: recipe for target all failed
make[1]: *** [all] Error 2
make[1]: Leaving directory /home/lucas/n64-master/build-gcc
makefile:117: recipe for target all-gcc failed
make: *** [all-gcc] Error 2
`
I attached my config.log from root and config.log from build-gcc for more detail. How can I fix this? I have also attached a screenshot of my error.

![Screenshot from 2019-06-12 22-12-08](https://user-images.githubusercontent.com/49287729/59405379-30b3a580-8d5f-11e9-8533-569696a8e474.png)

[config (root).log](https://github.com/glankk/n64/files/3284293/config.root.log)
[config (build-gcc).log](https://github.com/glankk/n64/files/3284295/config.build-gcc.log)

**Comment by shawlucas** [comment]
Nevermind, I fixed it. I was building from the root directory instead of from the build-gcc folder.

**Comment by yulong18** [comment]
Hi,
I want to sure that change the "--prefix" can avoid this error?
thank you!
